version: 2
jobs:
  build:
    working_directory: /dockerappnode
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            # apk add --no-cache py-pip=9.0.0-r1
            apk update && apk add nodejs
            # npm install docker-compose
            sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            # docker-compose run dockerapp python test.py
      # - deploy:
      #     name: Push application Docker image
      #     command: |
      #       docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      #       docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
      #       docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
      #       docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
      #       docker push $DOCKER_HUB_USER_ID/dockerapp:latest